set up linters
uwadonat/Newsweek pull request #1
Opened 2021-01-25 08:18 UTC by uwadonat

2021-01-25 17:41 UTC, Spayco requested changes
# Invalid 🛑 

Hello, you've made great progress, but I can't review your work unless the requirements below are met 👇 

- [ ] The project should have a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

* [ ] Pull Request has a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-25 21:56 UTC, BrittanyBlake commented
### Status: Invalid 🛑 
****
Hi @uwadonat and @Ghiftee. This pull request has been marked as invalid because your pull request is [not professional](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/). 

- Please ensure that your PR contains a meaningful title and a brief description of what you have done before you resubmit this pull request. 
****
Please make the required adjustments and submit a new code review request.

### Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2021-01-26 11:42 UTC, PhillipUg requested changes
Hey team, 👋

You have done an amazing job implementing the requirements for this project.

However, there are still some changes 👇 you need to implement before moving on to your next milestone 🔍

### Changes Required ♻️ 

- [ ] First of all, fix all linter errors. Kindly ensure to fix all linter errors before submitting for review in all your future projects

#### Header
- [ ] The Newsweek logo:
    -  is centered in desktop screen size
    -  In tablet and mobile, it is aligned to the left
* [ ] The Navbar contains a date only in desktop screen size
* [ ] Subscribe has a link
  - In mobile, the Login button changes into an icon
* [ ] The main navigation (menu)
  - Uses a nav tag
  - It has a form with the search field
  - In mobile and table the menu hides, and show a hamburger button
* [ ] The size of the elements change in desktop, tablet and mobile

#### Footer
* [ ] The social media icons have links
* [ ] The content-disposition changes to the correct place in desktop, tablet, and mobile

#### Please note that this request will be approved in the dashboard and you don’t need to submit it for re-review or merge this request into the main branch please make the suggested changes and move on to the next milestone. When you're done with the next milestone, submit this request again, don't create a new pull request. You are to keep submitting this same pull request until project completion.

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime** or
 <a href- [ ] ="mailto:phillipmusiime@gmail.com"> <img alt="gmail" src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social" target="_blank"></a> &nbsp; &nbsp; [![Twitter Follow](https://img.shields.io/twitter/follow/Phillip_Ug?style=social)](https://twitter.com/intent/follow?screen_name=Phillip_Ug) &nbsp; &nbsp; [![GitHub followers](https://img.shields.io/github/followers/phillipug?label=Follow&style=social)](https://github.com/PhillipUg)

2021-01-26 17:23 UTC, uwadonat commented
# linters have been checked
# footer icons are working as links
# main content added
# still working on responsiveness of the page.

2021-01-27 01:23 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @uwadonat and @uwadonat ! 👋 
Great job working on the requested changes!👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] Please make sure your project is responsive before resubmitting
- [ ] Some of your links are blue and underlines. Please ensure all of your links have no text decoration and are the same color as the rest of the text.
your clone 👇🏾 
<img width="850" alt="Screen Shot 2021-01-27 at 2 09 49 AM" src="https://user-images.githubusercontent.com/48804258/105927668-be332e80-6044-11eb-907c-74b7e26fcf1f.png">


- [ ] You are using a lot of css styling that can be done with bootstrap classes. Please take a look at this [cheat sheet](https://hackerthemes.com/bootstrap-cheatsheet/) and see what rules you can replace with bootstrap classes. 



- See my comments below for additional changes


****
### Please note that milestone 2 does not require a re-review and will be marked as approved in your dashboard, however these changes are MANDATORY. Please make the required changes before moving on to Milestone 3 🙏
Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2021-01-27 01:23 UTC, BrittanyBlake commented on styles.css
> +}
- [ ] This can be done using bootstrap classes

2021-01-27 01:23 UTC, BrittanyBlake commented on styles.css
> +  width: 100%;
- [ ] This can be done using the bootstrap class`w-100`

2021-01-27 01:23 UTC, BrittanyBlake commented on styles.css
> +  display: block;
- [ ] This can be done with the bootstrap class `d-block`

2021-01-27 01:23 UTC, BrittanyBlake commented on styles.css
> +  margin-right: auto;
- [ ] This can be done with the bootstrap classes `ml-auto` and `mr-auto`

2021-01-27 01:23 UTC, BrittanyBlake commented on styles.css
> +  text-decoration: none;
- [ ] This can be done with the bootstrap class`text-decoration-none`

2021-01-27 01:23 UTC, BrittanyBlake commented on styles.css
> +  list-style-type: none;
- [ ] This can be done with the bootstrap classes `d-flex flex-row justify-content-between` and `list-unstyled`

2021-01-27 01:23 UTC, BrittanyBlake commented on styles.css
> +}
- [ ] This can be done with bootstrap classes

2021-01-27 01:23 UTC, BrittanyBlake commented on styles.css
> +  color: black;
- [ ] This can be done with bootstrap classes

2021-01-27 01:23 UTC, BrittanyBlake commented on styles.css
> +}
- [ ] This can be done with the bootstrap class `mw-100`

2021-01-27 01:23 UTC, BrittanyBlake commented on styles.css
> +  float: left;
- [ ] This can be done with the bootstrap class `float-left`

2021-01-27 01:23 UTC, BrittanyBlake commented on styles.css
> +}
- [ ] This can be done with bootstrap classes

2021-01-27 01:23 UTC, BrittanyBlake commented on styles.css
> +}
- [ ] This can be done with the bootstrap class `text-left`

2021-01-27 01:23 UTC, BrittanyBlake commented on styles.css
> +}
- [ ] This can be done with bootstrap classes

2021-01-27 01:23 UTC, BrittanyBlake commented on styles.css
> +}
- [ ] This can be done with bootstrap classes

2021-01-27 01:23 UTC, BrittanyBlake commented on styles.css
> +  display: flex;
- [ ] This can be done with bootstrap classes

2021-01-27 23:13 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @uwadonat and @Ghiftee ! 👋 
Great job with your clone! You are almost done👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] You are still using a lot of css styling that can be done with bootstrap classes. Please take a look at this [cheat sheet](https://hackerthemes.com/bootstrap-cheatsheet/) and see what rules you can replace with bootstrap classes. 
Screenshot of the requirements 👇🏾 
<img width="410" alt="Screen Shot 2021-01-27 at 11 31 55 PM" src="https://user-images.githubusercontent.com/48804258/106063004-f03ca300-60cd-11eb-8e33-03feebd6b966.png">

- [ ] The images in the Main newspaper sections (US, World, etc.) should have a link, yours appear to be wrapped in div tags. 
screenshot from the requirements 👇🏾 

### Mobile 

- [ ] Your subscribe section should have 2 overlapping magazine covers 
- [ ] The text should be centered
your clone 👇🏾 
<img width="406" alt="Screen Shot 2021-01-28 at 12 01 30 AM" src="https://user-images.githubusercontent.com/48804258/106065725-12d0bb00-60d2-11eb-9118-0bb81d016355.png">
The original page 👇🏾 
<img width="413" alt="Screen Shot 2021-01-28 at 12 01 53 AM" src="https://user-images.githubusercontent.com/48804258/106065764-1fedaa00-60d2-11eb-87d4-bbcdcdf565ea.png">

- [ ] In your newsletter section, the image is missing 
- [ ] The text and button should be centered
Your clone 👇🏾 
<img width="412" alt="Screen Shot 2021-01-28 at 12 04 04 AM" src="https://user-images.githubusercontent.com/48804258/106065970-6e02ad80-60d2-11eb-955c-4a43815cd51d.png">
The original page 👇🏾 
<img width="415" alt="Screen Shot 2021-01-28 at 12 04 19 AM" src="https://user-images.githubusercontent.com/48804258/106065995-76f37f00-60d2-11eb-8919-4de39bcfcf60.png">

- [ ] Your footer is not quite right. The logo, text and social media icons should be left aligned and wrap under.
Your clone 👇🏾 
<img width="431" alt="Screen Shot 2021-01-28 at 12 06 13 AM" src="https://user-images.githubusercontent.com/48804258/106066156-bae68400-60d2-11eb-8347-c754b618aa20.png">
The original page 👇🏾 
<img width="421" alt="Screen Shot 2021-01-28 at 12 06 30 AM" src="https://user-images.githubusercontent.com/48804258/106066172-c46fec00-60d2-11eb-8bf8-0b32b1a5c004.png">

### Tablet
- [ ] Your subscribe section should have 2 overlapping magazine covers.
- [ ] There should be more spacing between the magazine covers and the text.
Your clone 👇🏾 
<img width="747" alt="Screen Shot 2021-01-28 at 12 09 54 AM" src="https://user-images.githubusercontent.com/48804258/106066458-3ea07080-60d3-11eb-9e7c-cca5eb9060af.png">
The original page 👇🏾 
<img width="767" alt="Screen Shot 2021-01-28 at 12 10 17 AM" src="https://user-images.githubusercontent.com/48804258/106066499-4c55f600-60d3-11eb-8799-2f07d6fa938b.png">

- [ ] The logo and copyright text should be left aligned.
Your clone 👇🏾 
<img width="774" alt="Screen Shot 2021-01-28 at 12 11 21 AM" src="https://user-images.githubusercontent.com/48804258/106066583-71e2ff80-60d3-11eb-857b-34268fd28fc6.png">
The original page 👇🏾 
<img width="760" alt="Screen Shot 2021-01-28 at 12 11 36 AM" src="https://user-images.githubusercontent.com/48804258/106066599-7b6c6780-60d3-11eb-9a6a-0a3d89c4b178.png">



****


- [ ] See my comments below for additional changes


****
Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2021-01-28 18:54 UTC, Spayco approved these changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] you still have some CSS properties that can be turned to Bootstrap classes (check previous TSE comments)
- [ ] The copyright text is merged with the logo in the tablet mode, please fix that 
![image](https://user-images.githubusercontent.com/11758151/106185035-9a85fa80-61a2-11eb-9b73-838ee8330ce5.png)


### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-29 10:30 UTC, uryelah requested changes
Hi **Donat Donat & Gift Uwhubetine**, I'm Sarah your reviewer for this PR 👩‍🚀 

You did an awesome job with this project! It's almost ready to go!

There are still a couple of issues to work on before moving forward to the next project but they will be pretty simple to implement, you already did the heavy lifting after all!

-------

## **Requested Changes ♻️**

**Carefully read the requests below and follow them before continuing to the next milestone**

- [ ] Please make sure all your linter checks are passing, that will ensure you are following the best industry standards in your code.

---------

    
    
**Keep being awesome devs and see you in the re-review!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2021-01-29 10:30 UTC, uryelah commented on index.html
> +    <nav id="nav-lg" class="container-fluid position-relative justify-content-between d-none bg-red d-lg-block">
- [ ] Please fix your navbar behavior on table and mobile sizes.
- The logo should still be showing up, change the size of the logo instead of simply using text.
- The items of the navbar should be aligned center in the y-axis.

**Your nav:**
![Screenshot_2021-01-29 NewsWeek(2)](https://user-images.githubusercontent.com/16193212/106263153-c507a000-6202-11eb-959d-39281d422835.png)


**How it should look like:**

![header_mobile](https://user-images.githubusercontent.com/16193212/106263220-da7cca00-6202-11eb-9f10-b1373c1eef45.png)

2021-01-29 10:30 UTC, uryelah commented on index.html
> +        </div>
- [ ] Add the separators between each footer link, the same way you have them in the header.
See how the footer should look like in the screenshot below(ignore the icons not loading):
![footer_desktop](https://user-images.githubusercontent.com/16193212/106263397-13b53a00-6203-11eb-981a-37bdc992ea38.png)

2021-01-29 10:30 UTC, uryelah commented on index.html
> +                  d="M58.7,10.8h-5.6v48.3H42.8l-25.1-33v22.1h5.6v10.8H0V48.3h5.6V10.8H0V0h17.6L41,30.7V10.8h-5.6V0h23.2	L58.7,10.8L58.7,10.8z M95.8,38c0,0.9,0,1.8-0.1,2.7H70.3c-0.7,8.2,2.4,10.6,7.1,1
- [ ] [OPTIONAL] Consider storing your svg in a svg file in your assets folder and calling it as an image to save up space at the index.html file.

2021-01-29 15:51 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @ . Thanks for submitting you project!

Great thing this project has and has done well:
:100:
:100:

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] The footer copyright is overlaping the logo
![image](https://user-images.githubusercontent.com/25774518/106296088-d65aa780-6216-11eb-84bc-f7b298363ee1.png)

- [ ] The elements on the navbar are not yet vertically center. To fix this you could use a bootstrap class for alignment.
![image](https://user-images.githubusercontent.com/25774518/106296278-13bf3500-6217-11eb-91dd-7eaae1c692dd.png)

- [ ] The alignment of the logo, copyright and social icons is uneven
- [ ] The Editions elements take more space than available, creating a horizontal scroll issue
![image](https://user-images.githubusercontent.com/25774518/106296530-6d276400-6217-11eb-965f-a62827c2f387.png)



## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2021-01-29 17:15 UTC, Spayco approved these changes
# Project Approved ✔️ 

thank you for making the required changes, your project is now approved!

- [ ] this is optional as it wasn't mentioned by the previous TSE, but please fix more of the CSS since there are a lot of CSS properties that can be a Bootstrap class instead, and this project is focused on that.

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-31 16:36 UTC, merged